config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'groups#index'
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :entities, only: [:index]
  end

  resources :entities, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :amount, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true, length: { maximum: 250 }

  belongs_to :user
  has_many :entities, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true
  validates :password, presence: true

  has_many :groups, dependent: :delete_all
  has_many :entities, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:first_name, :last_name,
                                             { address_attributes: %i[country state city area postal_code] }])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @entity = Entity.new
  end

  def create
    @groups = params[:entity][:group_id].drop(1)
    @groups.each do |group|
      @entity = Entity.new(name: params[:entity][:name], amount: params[:entity][:amount], group_id: group.to_i,
                           user_id: current_user.id)
      @entity.save
    end
    redirect_to group_path(@groups.first.to_i)
  end

  private

  def entity_params
    params.require(:entity).permit(:group_id, :amount, :name)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    return unless current_user

    @user = current_user
    @groups = @user.groups.includes(:entities)
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    render :new unless @group.save

    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/new.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center mt-5">
  <h1>Create a new transaction:</h1>
  <%= form_with model: @entity, url: entities_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Transaction name", required: true %>
      <%= form.label :name, 'Name', class: "form-label" %>
    </div>
    <div class="form-floating mb-3 w-100">
      <%= form.number_field :amount, class:"form-control", id:"floatingInput", placeholder:"Transaction amount", required: true  %>
      <%= form.label :amount, 'Amount', class: "form-label" %>
    </div>
    <%= form.label :group_id, 'Please select a category:', class: "form-label" %>
    <%= form.select :group_id, Group.order(:name).where(user:current_user).pluck(:name, :id), {}, {:multiple => true, required:true, :id => "groups", :class => "form-select mb-3" } %>
    <%= form.submit 'Create transaction', class: "btn btn-outline-success text-black" %>
  <% end %>
</div>

app/views/groups/index.html.erb
<% if current_user %>
  <div class="container-fluid d-flex flex-column align-items-center">
    <% unless @groups.empty? %>
      <% @groups.each do |group| %>
        <div class="card mt-2 mb-1" style="width: 95%;">
          <div class="card-body d-flex">
            <div>
              <img src=<%= group.icon %> class="category-icon me-2" alt="category icon">
            </div>
            <div class="w-75 d-flex justify-content-between align-items-center mx-2">
              <div class="d-flex flex-column justify-content-center">
                <%= link_to "#{group.name}", group_path(group.id), class:"card-title category-name fs-5 stretched-link" %>
                <p class="card-text mt-2"><small class="text-muted"><%=group.created_at.strftime("%d %b %Y")%></small></p>
              </div>
              <p class="card-text fw-semibold">$<%= group.entities.sum(:amount) %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3 class="mt-4">You don't have any categories yet.</h2>
    <% end %>
    <%= link_to 'Add a new category', new_group_path, class: "btn btn-outline-info text-black mt-5 py-2 px-5 fs-5" %>
  </div>
<% else %>
  <%= render partial: "shared/main" %>
<% end %> 

app/views/groups/new.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center mt-5">
  <h1>Create a new category:</h1>
  <%= form_with model: @group, url: groups_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Category name", required: true %>
      <%= form.label :name, 'Name', class: "form-label" %>
    </div>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :icon, class:"form-control", id:"floatingInput", placeholder:"Category icon", required: true%>
      <%= form.label :icon, 'Icon link', class: "form-label" %>
    </div>
    <%= form.submit 'Create category', class: "btn btn-outline-info text-black" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
  <div class="card" style="width: 95%;">
    <div class="card-header">
      <div class="d-flex align-items-center">
        <img src=<%= @group.icon %> class="category-icon me-4" alt="category icon">
        <h5 class="card-title category-name fs-5 stretched-link"><%=@group.name%>'s transactions</h5>
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between bg-light">
        <p class="m-1 gray-text fs-5">TOTAL PAYMENT</p>
        <p class="fw-semibold m-1 gray-text fs-5">$<%= @group.entities.sum(:amount) %></p>
      </li>
      <% unless @entities.empty? %>
        <% @entities.each_with_index do |ent, ind| %>
          <li class="list-group-item">
            <div d-flex flex-column>
              <p class="card-text gray-text">Transaction ID-<%=ind + 1%>: <span class="fw-semibold ms-2"><%=ent.name%></span></p>
              <p class="card-text gray-text">Amount: <span class="fw-semibold ms-2">$<%=ent.amount%></span></p>
              <p class="card-text mt-2"><small class="text-muted"><i class="fa-regular fa-calendar me-2"></i><%=ent.created_at.strftime("%d %b %Y")%> at <%=ent.created_at.strftime("%I.%M %p")%></small></p>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class="list-group-item gray-text">You don't have transactions here yet.</li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'Add a new transaction', new_entity_path, class: "btn btn-outline-info text-black my-5 py-2 px-5 fs-6" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/1dea6ac3ad.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= render partial: "shared/navbar" %>
    <% end %>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4 container-fluid w-50 d-flex flex-column align-items-center" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4 container-fluid w-50 d-flex flex-column align-items-center" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_main.html.erb
<div class="container-fluid d-flex flex-column align-items-center justify-content-center background-screen">
  <h1 class="mb-5 fs-1 background-logo">Budget Application</h1>
  <div class="d-flex w-50 justify-content-around mt-4">
    <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-light shadow fs-5" %>
    <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-light shadow fs-5" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="collapse primary-color text-white" id="navbarToggleExternalContent">
  <div class="collapse navbar-collapse d-flex flex-column align-items-center" id="navbarTogglerDemo01">
    <h1 class="navbar-brand fs-3 fw-semibold mt-4 mb-3">Budget Application</h1>
    <ul class="navbar-nav d-flex flex-column align-items-center me-auto mb-2 mb-lg-0 w-100">
      <li class="nav-item">
        <%= link_to "Categories", root_path, class: "nav-link active fs-6" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Categories", new_group_path, class: "nav-link active fs-6" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Transaction", new_entity_path, class: "nav-link active fs-6" %>
      </li>
    </ul>
    <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-danger my-2" %>
  </div>
</div>
<nav class="navbar navbar-dark primary-color mb-4">
  <div class="container-fluid d-flex justify-content-between">
    <button class="menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class=text-black><i class="fa fa-bars" aria-hidden="true"></i></span>
    </button>
    <h3 class="mt-2">
      <% if controller.controller_name == 'groups' && controller.action_name != 'show' %> Categories <% end %>
      <% if (controller.controller_name == 'groups' && controller.action_name == 'show') || controller.controller_name == 'entity' %> Transactions <% end %>
    </h3>
    <%= link_to '<i class=" fa fa-arrow-left"></i>'.html_safe, :back, class: " btn btn-alert"%>
  </div>
</nav>